import { Facility } from "./types";

export const Generations = [
  "Generation2",
  "Generation3",
  "Generation4",
  "Generation5",
  "Generation6",
  "Generation7",
  "Generation8",
] as const;

export const GenerationLabels = ["Gen2", "Gen3", "Gen4", "Gen5", "Gen6", "Gen7", "Gen8"] as const;

export const BattleFormats = ["Singles", "Doubles", "Multis"] as const;

export const discordLink = "https://discord.gg/7AfpxXArWv" as const;

export const facilities: Facility[] = [
  {
    id: "g4bts",
    label: "Battle Tower",
    generation: Generations[2],
    format: BattleFormats[0],
    firestoreCollection: "battle_tower_singles",
    category: ["monotype", "Little Cup"],
  },
  {
    id: "g4btd",
    label: "Battle Tower",
    generation: Generations[2],
    format: BattleFormats[1],
    firestoreCollection: "battle_tower_doubles",
    category: ["monotype", "Little Cup"],
  },
  {
    id: "g4btm",
    label: "Battle Tower",
    generation: Generations[2],
    format: BattleFormats[2],
    firestoreCollection: "battle_tower_multis",
    category: ["monotype", "Little Cup"],
  },
  {
    id: "g4btmai",
    label: "Battle Tower with AI",
    generation: Generations[2],
    format: BattleFormats[2],
    firestoreCollection: "battle_tower_ai_multis",
    category: ["monotype", "Little Cup"],
  },
  {
    id: "g4bfs50",
    label: "Battle Factory",
    generation: Generations[2],
    format: BattleFormats[0],
    firestoreCollection: "battle_factory_singles_50",
    category: ["L50", "L100", "never swap", "always swap"],
  },
  {
    id: "g4bfd50",
    label: "Battle Factory",
    generation: Generations[2],
    format: BattleFormats[1],
    firestoreCollection: "battle_factory_doubles_50",
    category: ["L50", "L100", "never swap", "always swap"],
  },
  {
    id: "g4bfm50",
    label: "Battle Factory",
    generation: Generations[2],
    format: BattleFormats[2],
    firestoreCollection: "battle_factory_multis_50",
    category: ["L50", "L100","never swap", "always swap"],
  },
  {
    id: "g4bcs",
    label: "Battle Castle",
    generation: Generations[2],
    format: BattleFormats[0],
    firestoreCollection: "battle_castle_singles",
    category: ["monotype", "Little Cup"],
  },
  {
    id: "g4bcd",
    label: "Battle Castle",
    generation: Generations[2],
    format: BattleFormats[1],
    firestoreCollection: "battle_castle_doubles",
    category: ["monotype", "Little Cup"],
  },
  {
    id: "g4bcm",
    label: "Battle Castle",
    generation: Generations[2],
    format: BattleFormats[2],
    firestoreCollection: "battle_castle_multis",
    category: ["monotype", "Little Cup"],
  },
  {
    id: "g4bas",
    label: "Battle Arcade",
    generation: Generations[2],
    format: BattleFormats[0],
    firestoreCollection: "battle_arcade_singles",
    category: ["monotype", "Little Cup"],
  },
  {
    id: "g4bad",
    label: "Battle Arcade",
    generation: Generations[2],
    format: BattleFormats[1],
    firestoreCollection: "battle_arcade_doubles",
    category: ["monotype", "Little Cup"],
  },
  {
    id: "g4bam",
    label: "Battle Arcade",
    generation: Generations[2],
    format: BattleFormats[2],
    firestoreCollection: "battle_arcade_multis",
    category: ["monotype", "Little Cup"],
  },
  {
    id: "g4bhs",
    label: "Battle Hall",
    generation: Generations[2],
    format: BattleFormats[0],
    firestoreCollection: "battle_hall_singles",
    category: ["monotype", "Little Cup"],
  },
  {
    id: "g4bhd",
    label: "Battle Hall",
    generation: Generations[2],
    format: BattleFormats[1],
    firestoreCollection: "battle_hall_doubles",
    category: ["monotype", "Little Cup"],
  },
  {
    id: "g4bhm",
    label: "Battle Hall",
    generation: Generations[2],
    format: BattleFormats[2],
    firestoreCollection: "battle_hall_multis",
    category: ["monotype", "Little Cup"],
  },
  {
    id: "g4btdps",
    label: "Battle Tower DP",
    generation: Generations[2],
    format: BattleFormats[0],
    firestoreCollection: "battle_tower_singles_DP",
    category: ["No PtHGSS moves"],
  },
  {
    id: "g4btdpd",
    label: "Battle Tower DP",
    generation: Generations[2],
    format: BattleFormats[1],
    firestoreCollection: "battle_tower_doubles_DP",
    category: ["No PtHGSS moves"],
  },
  {
    id: "g4btdpm",
    label: "Battle Tower DP-DP",
    generation: Generations[2],
    format: BattleFormats[2],
    firestoreCollection: "battle_tower_multis_DPDP",
    category: ["No PtHGSS moves"],
  },
  {
    id: "g4btdpai",
    label: "Battle Tower DP with AI",
    generation: Generations[2],
    format: BattleFormats[2],
    firestoreCollection: "battle_tower_ai_multis_DP",
    category: ["No PtHGSS moves"],
  },
  {
    id: "g4btdpmhg",
    label: "Battle Tower DP-PtHGSS",
    generation: Generations[2],
    format: BattleFormats[2],
    firestoreCollection: "battle_tower_multis_DPPT",
    category: ["No HGSS moves", "PtHGSS as leader"],
  },
    {
        id: "g2bts10",
        label: "Tower L10",
        generation: Generations[0],
        format: BattleFormats[0],
        firestoreCollection: "battle_tower_singles_L10",
        category: ["monotype", "Little Cup"],
    },
    {
        id: "g2bts20",
        label: "Tower L20",
        generation: Generations[0],
        format: BattleFormats[0],
        firestoreCollection: "battle_tower_singles_L20",
        category: ["monotype", "Little Cup"],
    },
    {
        id: "g2bts30",
        label: "Tower L30",
        generation: Generations[0],
        format: BattleFormats[0],
        firestoreCollection: "battle_tower_singles_L30",
        category: ["monotype", "Little Cup"],
    },
    {
        id: "g2bts40",
        label: "Tower L40",
        generation: Generations[0],
        format: BattleFormats[0],
        firestoreCollection: "battle_tower_singles_L40",
        category: ["monotype", "Little Cup"],
    },
    {
        id: "g2bts50",
        label: "Tower L50",
        generation: Generations[0],
        format: BattleFormats[0],
        firestoreCollection: "battle_tower_singles_L50",
        category: ["monotype", "Little Cup"],
    },
    {
        id: "g2bts60",
        label: "Tower L60",
        generation: Generations[0],
        format: BattleFormats[0],
        firestoreCollection: "battle_tower_singles_L60",
        category: ["monotype", "Little Cup"],
    },
    {
        id: "g2bts70",
        label: "Tower L70",
        generation: Generations[0],
        format: BattleFormats[0],
        firestoreCollection: "battle_tower_singles_L70",
        category: ["monotype", "Little Cup"],
    },
    {
        id: "g2bts80",
        label: "Tower L80",
        generation: Generations[0],
        format: BattleFormats[0],
        firestoreCollection: "battle_tower_singles_L80",
        category: ["monotype", "Little Cup"],
    },
    {
        id: "g2bts90",
        label: "Tower L90",
        generation: Generations[0],
        format: BattleFormats[0],
        firestoreCollection: "battle_tower_singles_L90",
        category: ["monotype", "Little Cup"],
    },
    {
        id: "g2bts100",
        label: "Tower L100",
        generation: Generations[0],
        format: BattleFormats[0],
        firestoreCollection: "battle_tower_singles_L100",
        category: ["monotype", "Little Cup"],
    },
    {
        id: "g3bts50",
        label: "Battle Tower",
        generation: Generations[1],
        format: BattleFormats[0],
        firestoreCollection: "battle_tower_singles_L50",
        category: ["L50", "L100","monotype", "Little Cup"],
    },
    {
        id: "g3btd50",
        label: "Battle Tower",
        generation: Generations[1],
        format: BattleFormats[1],
        firestoreCollection: "battle_tower_doubles_L50",
        category: ["L50", "L100","monotype", "Little Cup"],
    },
    {
        id: "g3btm50",
        label: "Battle Tower",
        generation: Generations[1],
        format: BattleFormats[2],
        firestoreCollection: "battle_tower_multis_L50",
        category: ["L50", "L100","monotype", "Little Cup"],
    },
    {
        id: "g3btsai50",
        label: "Battle Tower with AI",
        generation: Generations[1],
        format: BattleFormats[2],
        firestoreCollection: "battle_tower_ai_multis_L50",
        category: ["L50", "L100","monotype", "Little Cup"],
    },
    {
        id: "g3bds50",
        label: "Battle Dome",
        generation: Generations[1],
        format: BattleFormats[0],
        firestoreCollection: "battle_dome_singles_L50",
        category: ["L50", "L100","monotype", "Little Cup"],
    },
    {
        id: "g3bdd50",
        label: "Battle Dome",
        generation: Generations[1],
        format: BattleFormats[1],
        firestoreCollection: "battle_dome_doubles_L50",
        category: ["L50", "L100","monotype", "Little Cup"],
    },
    {
        id: "g3bfs50",
        label: "Battle Factory",
        generation: Generations[1],
        format: BattleFormats[0],
        firestoreCollection: "battle_factory_singles_L50",
        category: ["L50", "L100","monotype", "Little Cup"],
    },
    {
        id: "g3bfd50",
        label: "Battle Factory",
        generation: Generations[1],
        format: BattleFormats[1],
        firestoreCollection: "battle_factory_doubles_L50",
        category: ["L50", "L100","monotype", "Little Cup"],
    },
    {
        id: "g3bpike50",
        label: "Battle Pike",
        generation: Generations[1],
        format: BattleFormats[0],
        firestoreCollection: "battle_pike_singles_L50",
        category: ["L50", "L100","monotype", "Little Cup"],
    },
    {
        id: "g3bpyr50",
        label: "Battle Pyramid",
        generation: Generations[1],
        format: BattleFormats[0],
        firestoreCollection: "battle_pyramid_singles_L50",
        category: ["L50", "L100","monotype", "Little Cup"],
    },
    {
        id: "g3ba50",
        label: "Battle Arena",
        generation: Generations[1],
        format: BattleFormats[0],
        firestoreCollection: "battle_arena_singles_L50",
        category: ["L50", "L100","monotype", "Little Cup"],
    },
    {
        id: "g3bpals50",
        label: "Battle Palace",
        generation: Generations[1],
        format: BattleFormats[0],
        firestoreCollection: "battle_palace_singles_L50",
        category: ["L50", "L100","monotype", "Little Cup"],
    },
    {
        id: "g3bpald50",
        label: "Battle Palace",
        generation: Generations[1],
        format: BattleFormats[1],
        firestoreCollection: "battle_palace_doubles_L50",
        category: ["L50", "L100","monotype", "Little Cup"],
    },
    {
        id: "g3rsbt50",
        label: "Battle Tower RS",
        generation: Generations[1],
        format: BattleFormats[0],
        firestoreCollection: "battle_tower_singles_RS_50",
        category: ["L50", "L100","monotype", "Little Cup"],
    },
    {
        id: "g3rsbd50",
        label: "Battle Tower RS",
        generation: Generations[1],
        format: BattleFormats[1],
        firestoreCollection: "battle_tower_doubles_RS_50",
        category: ["L50", "L100","monotype", "Little Cup"],
    },
    {
        id: "g3rsbm50",
        label: "Battle Tower RS",
        generation: Generations[1],
        format: BattleFormats[2],
        firestoreCollection: "battle_tower_multis_RS_50",
        category: ["L50", "L100","monotype", "Little Cup"],
    },
    {
        id: "g3rsbmai50",
        label: "Battle Tower RS with AI",
        generation: Generations[1],
        format: BattleFormats[2],
        firestoreCollection: "battle_tower_ai_multis_RS_50",
        category: ["L50", "L100","monotype", "Little Cup"],
    },
    {
        id: "g5s",
        label: "Battle Subway",
        generation: Generations[3],
        format: BattleFormats[0],
        firestoreCollection: "battle_subway_singles",
        category: ["monotype", "Little Cup"],
    },
    {
        id: "g5d",
        label: "Battle Subway",
        generation: Generations[3],
        format: BattleFormats[1],
        firestoreCollection: "battle_subway_doubles",
        category: ["monotype", "Little Cup"],
    },
    {
        id: "g5m",
        label: "Battle Subway",
        generation: Generations[3],
        format: BattleFormats[2],
        firestoreCollection: "battle_subway_multis",
        category: ["monotype", "Little Cup"],
    },
    {
        id: "g5sai",
        label: "Battle Subway with AI",
        generation: Generations[3],
        format: BattleFormats[2],
        firestoreCollection: "battle_subway_ai_multis",
        category: ["monotype", "Little Cup"],
    },
    {
        id: "g6s",
        label: "Battle Maison",
        generation: Generations[4],
        format: BattleFormats[0],
        firestoreCollection: "battle_maison_singles",
        category: ["monotype", "Little Cup"],
    },
    {
        id: "g6d",
        label: "Battle Maison",
        generation: Generations[4],
        format: BattleFormats[1],
        firestoreCollection: "battle_maison_doubles",
        category: ["monotype", "Little Cup"],
    },
    {
        id: "g6m",
        label: "Battle Maison",
        generation: Generations[4],
        format: BattleFormats[2],
        firestoreCollection: "battle_maison_multis",
        category: ["monotype", "Little Cup"],
    },
    {
        id: "g6sai",
        label: "Battle Maison with AI",
        generation: Generations[4],
        format: BattleFormats[2],
        firestoreCollection: "battle_maison_ai_multis",
        category: ["monotype", "Little Cup"],
    },
    {
        id: "g6r",
        label: "Battle Maison Rotation",
        generation: Generations[4],
        format: BattleFormats[1],
        firestoreCollection: "battle_maison_rotation",
        category: ["monotype", "Little Cup"],
    },
    {
        id: "g6t",
        label: "Battle Maison Triples",
        generation: Generations[4],
        format: BattleFormats[1],
        firestoreCollection: "battle_maison_triples",
        category: ["monotype", "Little Cup"],
    },
    {
        id: "g7s",
        label: "Battle Tree",
        generation: Generations[5],
        format: BattleFormats[0],
        firestoreCollection: "battle_tree_singles",
        category: ["monotype", "Little Cup"],
    },
    {
        id: "g7d",
        label: "Battle Tree",
        generation: Generations[5],
        format: BattleFormats[1],
        firestoreCollection: "battle_tree_doubles",
        category: ["monotype", "Little Cup"],
    },
    {
        id: "g7m",
    label: "Battle Tree",
    generation: Generations[5],
    format: BattleFormats[2],
    firestoreCollection: "battle_tree_multis",
    category: ["monotype", "Little Cup"],
    },
    {
        id: "g7sai",
        label: "Battle Tree with AI",
        generation: Generations[5],
        format: BattleFormats[2],
        firestoreCollection: "battle_tree_ai_multis",
        category: ["monotype", "Little Cup"],
    },
    {
        id: "g8s",
        label: "Battle Tower",
        generation: Generations[6],
        format: BattleFormats[0],
        firestoreCollection: "battle_tower_singles",
        category: ["classic", "no dynamax", "monotype", "Little Cup"],
    },
    {
        id: "g8d",
        label: "Battle Tower",
        generation: Generations[6],
        format: BattleFormats[1],
        firestoreCollection: "battle_tower_doubles",
        category: ["classic", "no dynamax", "monotype", "Little Cup"],
    },
    {
        id: "g8rs",
        label: "Restricted Sparring",
        generation: Generations[6],
        format: BattleFormats[0],
        firestoreCollection: "restricted_sparring_singles",
        category: ["Little Cup"],
    }
];
